# Copyright (C) 2015-2016 Texas Instruments Incorporated - http://www.ti.com/
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-${CONFIG_TI_I2C_BOARD_DETECT} += board_detect.o
obj-${CONFIG_TARGET_AM335X_NETBIRD} += board_detect_netbird.o
